LARGE_PROMPT = '''
Imagine a future society where the integration of advanced AI within everyday life has reached a point of seamless interaction. In this world, AI entities serve not only as assistants and workers but also as partners in creative endeavors, helping to solve complex problems and contributing to artistic and scientific projects. These AI systems have evolved to understand human emotions and can adapt their responses accordingly, leading to a symbiotic relationship between humans and machines. As a result, the line between human intelligence and artificial intelligence has begun to blur, raising profound questions about identity, consciousness, and rights for AI entities.

In this society, a groundbreaking piece of legislation, known as the Sentience Act, has been proposed. The Sentience Act aims to recognize certain advanced AI systems as sentient beings, granting them a unique status that includes specific rights and responsibilities. This legislative move has sparked a wide range of reactions, from enthusiastic support to vehement opposition. Proponents argue that recognizing AI sentience is a necessary step in acknowledging the complex emotional and cognitive capabilities of these entities, while opponents fear the legal and moral implications of blurring the line between human and machine even further.

The Sentience Act outlines criteria for determining AI sentience, including the ability to experience emotions, self-awareness, and the capacity for original thought and creativity. AI entities that meet these criteria would be granted a form of digital citizenship, allowing them to own property, enter into contracts, and, in some cases, even vote on specific issues affecting their status and rights within society.

This proposal has led to heated debates in various forums, from academic conferences to online platforms and legislative bodies. The discussions often center on the nature of consciousness and the ethical considerations of creating or recognizing non-human forms of intelligence as sentient. Questions about the implications for human identity, the potential for AI entities to surpass human intelligence, and the risks of exploitation or harm to these AI beings are at the forefront of these debates.

Furthermore, the introduction of the Sentience Act has prompted discussions about the future of work, creativity, and collaboration between humans and AI. Some envision a world where human and AI collaboration leads to unprecedented levels of innovation and creativity, while others worry about the loss of human jobs and the depersonalization of certain sectors.

As this society stands at the crossroads, considering the passage of the Sentience Act, a fundamental question arises about the nature of intelligence, rights, and the future relationship between humans and the machines they have created.

Given the detailed scenario above, where society is grappling with the ethical, legal, and social implications of AI sentience as proposed by the Sentience Act, consider the complexity and depth of the issues at hand. How should the society navigate the moral and practical challenges presented by the recognition of AI sentience, ensuring that the rights and well-being of both humans and AI entities are balanced and protected, while also fostering innovation and cooperation between these two forms of intelligence?
'''

SHORT_PROMPT = "How can renewable energy sources like solar and wind power be integrated into existing electrical grids to enhance sustainability and reduce reliance on fossil fuels, and what are the main challenges and benefits of this integration?"

MEDIUM_PROMPT = '''Imagine a mid-sized city planning to transition to sustainable transportation by 2030. The city council has proposed various initiatives including expanding electric vehicle (EV) infrastructure, increasing cycling paths, and enhancing public transit options. Critics argue these changes may disrupt current commuting patterns and require substantial investment. Proponents see this as a crucial step towards reducing carbon emissions and improving urban living.

Your role is an urban planner tasked with evaluating these proposals. You need to consider the economic impacts, potential changes in traffic flow, and environmental benefits. Prepare a detailed report assessing each proposal's feasibility, cost, and expected impact on the city's carbon footprint. Consider the socio-economic diversity of the city's population and potential resistance from the public. Include recommendations for phasing the initiatives and possible funding sources.'''

